### ISSUE TITLE
PPcheck hangs at waiting for y_rep

### ISSUE THREAD

**Issue by jgabry** [stan-dev/shinystan#107]
Reported by Gene Quinn on stan-users:

https://groups.google.com/forum/#!topic/stan-users/KZuToKLfKAM

**Comment by rubenarslan** [comment]
I have the problem with fits from brms launched through brms::launch_shiny, but not with rstanarm fits launched via rstanarm::launch_shinystan, so if you can't reproduce it, maybe it's on @paul-buerkner's side and Gene Quinn did not mention this.

**Comment by jgabry** [comment]
Thanks for reporting. I still haven't been able to reliably reproduce this
problem so it's been difficult to debug. Haven't forgotten about it though.
When used with rstanarm models, shinystan lets rstanarm generate the plots
for the graphical posterior predictive checks (i.e., rstanarm creates the
ggplot objects and then shinystan just displays them), so that might be why
there's no issue when using rstanarm models.

**Comment by rubenarslan** [comment]
That would explain it at least. @paul-buerkner told me hadn't implemented it yet, but since the interface looks the same otherwise, it's easy to get mixed up. But you should probably ask Gene Quinn whether that was the case for him too.

**Comment by jgabry** [comment]
Gene's example wasn't brms related (just regular rstan with a .stan file)
but it's possible (likely even) that it turns out to be the same problem
under the hood.

**Comment by jgabry** [comment]
Does this happen with every brms model you try or just with certain ones?

**Comment by rubenarslan** [comment]
All so far, including gaussian and forked families. Tried maybe 5.

**Comment by jgabry** [comment]
Ok thanks. I try a few from brms and maybe that will help diagnose this. So
far I had just been testing with regular rstan models.

**Comment by paul-buerkner** [comment]
I am more than happy to help if needed. However, I currently don't see how brmsfit objects could be used with PPcheck of shinystan. The reason is that they do not contain a parameter with the y_rep values, because this would lead to models of multiple GBs for larger models. Instead, we have the predict method that generates those values within R, but those values cannot be included inside PPcheck of shinystan as y_rep, since they are not part of the model itself.

**Comment by jgabry** [comment]
Ok that makes sense. So this brms issue is separate from the original
issue.

I think I've finally solved the original issue, so I'm going to close this
after I test it, but if you want can you open a new issue for allowing the
PPcheck page to accept yrep from the user in the same way it does for y? I'm
definitely open to adding that functionality, which would allow it to work
with your package and be useful in general.

**Comment by paul-buerkner** [comment]
That would certainly be great! I will open another issue for this. :-)

**Comment by jgabry** [comment]
I just posted a reply to the original post on stan-users, which I'll copy here: 

<blockquote>
Hi Gene, 

<p> Sorry for the delay, but I've finally got this sorted out. The problem is that your y_rep doesn't have the right dimensions but ShinyStan was just waiting for an object with the correct dimensions instead of issuing a warning. I'm going to fix that so the warning appears. You can get the PPcheck page to work for your model if you make a slight tweak to your Stan code. The problem is that you have y declared as a real array with Nobs elements but y_rep is only declared as a scalar real. y_rep should have the same dimensions as y, so you can just change your generated quantities block to </p>

<pre>
generated quantities{
  real y_rep[Nobs];
  for (n in 1:Nobs)
    y_rep[n] <- gamma_rng(alpha,beta);
}
</pre>

<p> and then you'll be getting the right posterior predictive distribution and ShinyStan's PPcheck should work for you. </p>

Jonah
</blockquote>

I'm going to close this and open a new issue for adding the appropriate warning about dimensions.
