### ISSUE TITLE
Shinystan breaks under new ggplot2 (2.0)

### ISSUE THREAD

**Issue by saudiwin** [stan-dev/shinystan#108]
This could be an easy fix, but under the new ggplot2 version 2.0, launch_shinystan fails with the following message:

Error in get(x, envir = ns, inherits = FALSE) : object 'coord' not found

It still opens a browser window to display the model, but there is no web site displayed (HTTP 500 error).

Options(error=recover) yields the following:

1: launch_shinystan(all_fits[[40]])
2: launch(object, rstudio, ...)
3: shiny::runApp(system.file("ShinyStan", package = "shinystan"), launch.browser = launch.browser, ...)
4: shinyCallingHandlers(while (!.globals$stopped) {
    serviceApp()
    Sys.sleep(0.001)
})
5: withCallingHandlers(expr, error = function(e) {
    handle <- getOption("shiny.error")
    if (is.function(handle)) 
  
6: serviceApp()
7: timerCallbacks$timeToNextEvent()
8: dim(.times)
9: dim.data.frame(.times)

Selecting option 9 shows the following function:

function (x) 
c(.row_names_info(x, 2L), length(x))

Sorry I can't be of more help. Uninstalling ggplot2 2.0 and re-installing 1.0 or 1.1 from source resolves the problem.

**Comment by jgabry** [comment]
Thanks for reporting. Can you try installing the version-2.0.2 branch of
shinystan from github using the devtools package:

devtools::install_github("stan-dev/shinystan", ref = "version-2.0.2")

I think these issues are fixed on that branch, which we'll be submitting
this week. The ggplot2 update has been a bit of pain to deal with so it'd
be helpful to know if this version of shinystan works for you. Thanks.

**Comment by jkbest2** [comment]
The version-2.0.2 branch solved this problem for me.

**Comment by jgabry** [comment]
Ok great. Thanks for letting us know.

**Comment by saudiwin** [comment]
I'm currently running a simulation so I can't test the new shinystan
package on my machine for a day or so, but I will let you know once I have
the opportunity.

**Comment by jgabry** [comment]
Ok this should be fixed now on the develop branch and will be in the next release. @saudiwin If by any chance it's still not fixed for you please reopen this issue. Thanks!

**Comment by saudiwin** [comment]
Thanks for addressing it!
