### ISSUE TITLE
Error: "loop_apply" not resolved from current namespace (plyr)

### ISSUE THREAD

**Issue by cvr7** [stan-dev/shinystan#111]
Greetings, when I use launch_shinystan() some of the results appear but most of the figures are missing with the error message on the screen where the figure should be of: Error: "loop_apply" not resolved from current namespace (plyr)

Does anyone know how I can resolve this? Thanks.

**Comment by jgabry** [comment]
I've seen this error before, but only in older versions of shinystan. Which version of the package does `packageVersion("shinystan")` say you have? Also can you share the results you get when you call `sessionInfo()` after you get the error? Thanks.

**Comment by cvr7** [comment]
That was it... I had an old version of shinystan, 2.0.0, installed shinystan 2.1.0 and it now works perfectly.  Thanks.

**Comment by jgabry** [comment]
Ok great, glad that fixed it.
