### ISSUE TITLE
Clear selectize box

### ISSUE THREAD

**Issue by dmenne** [stan-dev/shinystan#114]
There should be some way to clear the selectize box for parameters. In case the feature is there already, some short help text would be nice.

**Comment by jgabry** [comment]
You should be able to use typical keyboard shortcuts. For example, clicking anywhere in the selectize box and then using cmd+a works on my mac to select all (I assume cntrl+a on windows). Then you can just hit delete on your keyboard. Does that work for you?

**Comment by dmenne** [comment]
I should have known. When I write Shiny programs, I normally have a clear button. 
Two minor points on the same subject:

- Add a popup or comment that regexp can be used
- On my machine (Windows 7), the field is too low

![2016-02-17 08_23_52-shinystan](https://cloud.githubusercontent.com/assets/506275/13102576/02913b6a-d550-11e5-945d-5d32b2ef6774.png)

**Comment by jgabry** [comment]
Thanks for the tips. It should say "Add parameters by regex search" in the
"Search" field by default but if the text box is too small or the text is
too low I guess that's not very helpful. I'll try to fix that so it's
visible.

**Comment by jgabry** [comment]
@dmenne If you install shinystan from the develop branch is the text more readable in the Search field?

**Comment by dmenne** [comment]
Fine. Even if I would prefer the text in small font above the box to avoid erasing, and to keep it there as a reminder.

**Comment by jgabry** [comment]
Indeed, maybe having it above the box would be better. I'll give that a try.

**Comment by jgabry** [comment]
@dmenne Ok, I put the label above the search box (on develop branch). I agree that it's better this way. Thanks for the suggestion. If it looks ok for you on windows then I'll close this issue.

**Comment by dmenne** [comment]
Left aligned with the edit box? (nitpick off). Looks good.

**Comment by jgabry** [comment]
> Left aligned with the edit box?

Yeah I noticed that. I just tweaked some CSS so it's aligned better.
