### ISSUE TITLE
Trivariate plot

### ISSUE THREAD

**Issue by csgillespie** [stan-dev/shinystan#119]
When you first click on the trivariate plot, you get paramater1 vs parameter1 vs log-post.

If would be more helpful if the default was parameter1 vs parameter2 vs log-post

**Comment by jgabry** [comment]
Thanks. I think the reason the default is that way is so it doesn't error if the model has only a single parameter. But it shouldn't be hard to check the number of parameters and then default to the parameter2 so long as a parameter2 exists.
