### ISSUE TITLE
Allow subsetting of model params when making shinystan object

### ISSUE THREAD

**Issue by RalphAS** [stan-dev/shinystan#122]
It would be useful to limit the variables converted from `stanfit` to shinystan, e.g. by use of the `pars` and `include` options found elsewhere in `rstan`.  For example, one often generates thousands of variables for model evaluation (loo, waic) which get in the way of diagnosing the sampling. Currently one can go by way of an `mcmc.list`, but that loses the NUTS/HMC details.

**Comment by jgabry** [comment]
Thanks, I agree. Currently on the develop branch there's a drop_parameters
function that kind of does what you're talking about. Unfortunately you
first need to create a shinystan object and then it will let you drop the
parameters. This will make launching shinystan much faster but it might
still take a while to create the initial object. It should be possible to
combine this into a single step, but I just haven't had the chance to do it
yet. Definitely on the to-do list.

**Comment by jgabry** [comment]
In addition to the new `drop_parameters` function I've also added a `pars` argument to `as.shinystan` for selecting a subset of parameters when creating a shinystan object from a stanfit object. This should be included in the next release (which I expect will come out within the next week or two)

**Comment by zhenzuo2** [comment]
For the variables in pars, some variables are vectors. Is it possible to only show first 10 dimensions rather than the whole variables. Thanks.
