### ISSUE TITLE
plot for `energy__` diagnostic 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/shinystan#127]
Overlaid histogram of `energy__` and `first_diff(energy__)` to show a visual representation of BFMI

**Comment by jgabry** [comment]
http://arxiv.org/pdf/1604.00695.pdf

**Comment by bgoodri** [comment]
Was this implemented?

**Comment by jgabry** [comment]
It's implemented in bayesplot and I'm planning on using that plot in
shinystan. Just need to actually add it.
