### ISSUE TITLE
ShinyStan not outputting estimates

### ISSUE THREAD

**Issue by cvr7** [stan-dev/shinystan#131]
[shinystan.docx](https://github.com/stan-dev/shinystan/files/445533/shinystan.docx)

when running shinystan now I've been having issues with all the plots showing up, it will say "loading" (see attachment) and when looking at table of estimates the following error occurs (the latex table generated is fine).

Error: 'copySWF' is not an exported object from 'namespace:DT'

**Comment by jgabry** [comment]
Thanks for reporting this. I think this is related to
https://github.com/stan-dev/shinystan/issues/130 and should be fixed on the
develop branch already (and will be in next release). For now you should be
able to install it using

devtools::install_github("stan-dev/shinystan", ref = "develop")

Hopefully that resolves the issue, but if you could let us know either way
that would be helpful.

Thanks!

Jonah

**Comment by jgabry** [comment]
Closing this and submitting patched version for release. If the problem persists we can definitely reopen this.
