### ISSUE TITLE
Error in static HMC fit

### ISSUE THREAD

**Issue by colemonnahan** [stan-dev/shinystan#134]
When I run the models:

````
hmc.fit <- stan(file='centered.stan', data=data, chains=1, iter=2000, thin=1,
             algorithm='HMC')
nuts.fit <- stan(file='centered.stan', data=data, chains=1, iter=2000, thin=1)
````
and then plug those into `launch_shinystan`, the NUTS model works fine but the HMC one gives me this error:

````
Warning: Error in [: subscript out of bounds
Stack trace (innermost first):
    46: FUN [helper_functions/hmc_diagnostics_helpers.R#6]
    45: lapply
    44: .sampler_param_pw [helper_functions/hmc_diagnostics_helpers.R#5]
    43: eval [server_files/utilities/extract_sso.R#43]
    42: eval
    41: withVisible
    40: source
     3: shiny::runApp
     2: launch
     1: launch_shinystan
Error in sp[[i]][, which] : subscript out of bounds
````
I'm using R 3.2.3, rstan 2.11.1 and shinystan 2.2.1.

Am I doing something dumb here or is this a bug?

**Comment by colemonnahan** [comment]
I should have noted that if I use a different number of chains the same error occurs.

**Comment by jgabry** [comment]
Thanks for letting us know. This is definitely a bug, but it shouldn't be
hard to fix. I'll hopefully be able to get to it today.

**Comment by jgabry** [comment]
I think this was even simpler than I anticipated. Should be fixed now if you install from github with 

```r
devtools::install_github("stan-dev/shinystan")
```

**Comment by colemonnahan** [comment]
The bug has been fixed. Thank you.

**Comment by jgabry** [comment]
Great. Thanks again for reporting it.

**Comment by colemonnahan** [comment]
@jgabry No problem. Thanks for the great tool.

I also noticed an error in the bivariate option in the explore tab. But I imagine not many people use static HMC. If you want me to report it separately I can, but it doesn't affect what I need to do at the moment.

**Comment by jgabry** [comment]
Thanks, whenever you have a chance if you don't mind opening an issue for
the bivariate error you're seeing that would be great. I do think static
HMC is rare (as it probably should be) but I'd still like to make sure it's
functioning properly.

Thanks again,

Jonah
