### ISSUE TITLE
Adding new class to shinystan

### ISSUE THREAD

**Issue by colemonnahan** [stan-dev/shinystan#136]
I'm working with a software tool that does static HMC and NUTS that is _not_ Stan. After using shinystan to investigate model fits, particularly for NUTS, I don't think I can go back. 

So it seems like the best thing would be to either 
1. Manually construct a shinystan object with `shinystan`. For example, filling out `param_names`, `summary`, etc. to match what Stan produces.
2. Make a new class for `as.shinystan` that would do this work.

I see the downside of the second is that you'd have to maintain it in the package. The plus side is that users of this software will just have to install shinystan.

Thoughts on the best way to approach this?

**Comment by jgabry** [comment]
How much do you care about being able to view the table of HMC sampler summary statistics (second tab on the Diagnose page)? For static HMC that might be the only difference between what you get from using a model fit with Stan vs. creating a shinystan object using the `as.shinystan` method for arrays (only requires a 3-D array of posterior draws) or for lists (only requires a list of matrices of posterior draws).

**Comment by colemonnahan** [comment]
Not that much. I was mostly using static HMC as a simpler test case than NUTS. The latter will, as with Stan, be the default and predominantly used algorithm by the user base. So in the end that's all I really will care about.

I'm currently implementing NUTS in the software, so I have the option to structure the output in a way that easily facilitates conversion to a shinystan object. I thought I'd first get sHMC working with shinystan and understand it's inputs, and take any lessons learned to the development of NUTS. Hopefully that makes sense.

I proposed the idea of coercing the NUTS output into a stanfit object, but the stan-dev team didn't [think that was a good idea](https://groups.google.com/forum/#!searchin/stan-dev/monnahan%7Csort:relevance/stan-dev/YxfUvewueOY/V_BYnoYwAAAJ), and recommended skipping straight to shinystan.

**Comment by jgabry** [comment]
I think I should allow the as.shinystan method for arrays to also accept an
additional argument for passing in sampler diagnostic info. So it would
look something like

as.shinystan(X, sampler_params = your_sampler_params, algorithm = "NUTS")

or something like that. X would be the posterior draws of the parameters
and your_sampler_params would be a list of matrices like what you get from
get_sampler_params(stanfit). Then it would return a shinystan object
similar to the one you would get if you had used Stan. So all you would
need to do would be to put the NUTS parameters in the get_sampler_params
format.

This wouldn't be too hard for me to implement so I could probably get it
into the next version of shinystan. If I understand your use case correctly
that would be sufficient, right?

>

**Comment by colemonnahan** [comment]
Yes that sounds like a great compromise that I hadn't thought of. So sampler_params here would be an array matching the dimensions (chains) of X? I would also suggest passing `misc` which contains max treedepth, since exceeding that can be a useful diagnostic.

I know there are some other programs out there that can do NUTS too, so this would be an attractive option for them as well.

**Comment by jgabry** [comment]
Yeah I'll also allow the user to provide a value for `max_treedepth`.

**Comment by colemonnahan** [comment]
THanks @jgabry. I'm available to test if that would help.

**Comment by jgabry** [comment]
I think the `feature-issue-136` branch might be ready for you to try it out if you want. Here's an example: 

```r
fit <- stan_demo("eight_schools")
posterior <- extract(fit, inc_warmup = TRUE, permuted = FALSE) # 3-D array
nuts_stuff <- get_sampler_params(fit) # list of matrices

# now create shinystan object without needing the stanfit object
sso <- as.shinystan(
  posterior, 
  burnin = 1000, 
  sampler_params = nuts_stuff, 
  max_treedepth = 11,
  algorithm = "NUTS"
)
launch_shinystan(sso)
```

**Comment by colemonnahan** [comment]
@jgabry I have tested this branch with static HMC and NUTS generated using an alternative software implementation than Stan. In both cases the shinystan functionality worked as expected.

If you merged this feature into the main branch (and later CRAN) that would be really helpful for me and my community.

Thanks,
Cole

**Comment by jgabry** [comment]
That's great, thanks for following up. I might tweak argument names or how
things are specified (probably not much) but I plan on getting this
functionality into the next CRAN release. Glad it will be useful!

Jonah

**Comment by jgabry** [comment]
@colemonnahan Finally got a PR together for this (#143). I'm not sure when the next release will be but definitely this winter. Sorry for the delay.

**Comment by colemonnahan** [comment]
@jgabry Much appreciated. I'll have people install directly from github in the interim, which is no problem.

**Comment by jgabry** [comment]
Ok cool. I try to keep the master branch at the state of the current CRAN
release but I'll get the PR merged into the (stable) develop branch ASAP.
Once I do that people can then install from GitHub in the normal way but
adding ref="develop" to the install_github command.

**Comment by colemonnahan** [comment]
OK thanks, that works fine for me.

**Comment by jgabry** [comment]
Ok should be installable from the develop branch now.

**Comment by jgabry** [comment]
@colemonnahan Just released the update that includes this functionality. It's on CRAN now but binaries probably haven't built yet.

**Comment by colemonnahan** [comment]
Roger, thanks for the update.
