### ISSUE TITLE
Subscript error in static HMC

### ISSUE THREAD

**Issue by colemonnahan** [stan-dev/shinystan#137]
Following up on issue #134, I now get an error with the Bivariate plot in Explore. The browser shows "Error: subscript out of bounds" and the console shows:

````
Warning: Error in [: subscript out of bounds
Stack trace (innermost first):
    118: FUN [helper_functions/shinystan_helpers.R#628]
    117: lapply
    116: sapply
    115: .bivariate_plot [helper_functions/shinystan_helpers.R#628]
    114: do.call
    113: <reactive:bivariate_plot> [server_files/pages/explore/server/bivariate.R#37]
    102: bivariate_plot
    101: renderPlot [server_files/pages/explore/server/bivariate.R#65]
     91: <reactive:plotObj>
     80: plotObj
     79: origRenderFunc
     78: output$bivariate_plot_out
      3: shiny::runApp
      2: launch
      1: launch_shinystan
````
This error occurs for all parameter combinations that I've tried, including the default.

Interestingly, the Trivariate plots seems to work just fine, in addition to the Density and Histogram plots. I don't see any other issues with Diagnose or Estimate views.

**Comment by jgabry** [comment]
Thanks should be fixed now.
