### ISSUE TITLE
allow users to add their own plots to personal panel 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/shinystan#14]
Add a new tab for displaying user's personal plots. They can add plots by
- pointing shinyStan to a ggplot2 object in their R global environment
- uploading .RData file containing a ggplot2 object
- upload an image (e.g. png, etc.)

**Comment by bob-carpenter** [comment]
Given that R allows functions as arguments, you might even allow
this to take a function definition from the user that maps a 
sample to a plot --- then it could potentially be redrawn if Stan's
re-run.

**Comment by jgabry** [comment]
Now that's a cool idea!
