### ISSUE TITLE
Allow for member of global objects in graphical posterior check

### ISSUE THREAD

**Issue by dmenne** [stan-dev/shinystan#141]
In "Graphical posterior predictive check", I have to select a global object for observations. I always pass in a data list, and to use it in PPC, I have to make a copy of the element.

Wish:
-- Either open a second box with the list elements when the selected global is a list
-- Or: allow data$y notation manually entered in box

**Comment by jgabry** [comment]
Thanks for the suggestion. I've been thinking that it might make sense to
associate the outcome variable with the shinystan object. In that case
there could be an extra argument to as.shinystan that allows passing an
outcome variable that shinystan will use will on the PPcheck page. I think
that would solve your problem too, right?

**Comment by dmenne** [comment]
It would solve the problem, but having a separate combo opening when you choose a list element is more flexible and better separates tasks. Passing an extra variable is a bit more limited, but it could require less clicking. 
Both sounds ok, though,
