### ISSUE TITLE
Typo in "Estimate" Tab

### ISSUE THREAD

**Issue by ruedin** [stan-dev/shinystan#146]
In the "Estimate" tab, there is a typo: it says "Kernal density estimates" rather than "Kernel density estimates".

Steps to reproduce:
1. launch shinystan
2. click on "Estimate"
3. click on "Show/Hide Options"

This is Version 2.2.1

**Comment by jgabry** [comment]
Thanks for pointing that out. I'll get that fixed. I've looked at it so
many times and never noticed!
