### ISSUE TITLE
Make launch_shinystan S3 generic

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/shinystan#148]
To support shinystan in other packages, one has to use another name than `launch_shinystan` as the latter only supports certain object types. I think this is suboptimal, but may easily be changed by making `launch_shinystan` an S3 generic function.

**Comment by jgabry** [comment]
Hey Paul, yeah this occurred to me a while ago but I forgot to open an
issue to remind myself apparently. Glad you brought it up again. I think a
generic launch_shinystan() is a good idea.
