### ISSUE TITLE
shinystan not working

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/shinystan#151]
For me (on Linux) launch_shinystan() whether in the browser or RStudio does launch but doesn't do anything when you click on a menu item (although it does amend the URL). Below are the messages from the developer console of Chrome:
![image](https://user-images.githubusercontent.com/3386282/28656896-64dbdde6-7272-11e7-9f5d-a76293c29f8f.png)

**Comment by jgabry** [comment]
That's no good. It's working for me on Mac (I just tried on Chrome, Safari, and Firefox) so I'm not able to reproduce this but maybe I'll be able to figure it out from those Chrome messages. What's your sessionInfo()?

**Comment by jgabry** [comment]
Have you tried any other browsers on Linux? It'd be good to know if this is specific to Chrome or not.

**Comment by bgoodri** [comment]
It definitely also happens with the RStudio browser.

**Comment by jgabry** [comment]
Hopefully I'll be able to fix it from my Mac by looking into that output
from Chrome, but it might be tough to fix without being able to replicate
it. I may need to come by when I'm back from Chicago and look at what's
happening when it's run on your Linux system.

**Comment by jgabry** [comment]
@bgoodri what version of RStudio's **shiny** package do you have?

**Comment by jgabry** [comment]
If you don't have shiny 1.0.3 try updating and see if that gets it working

**Comment by bgoodri** [comment]
That allows me to get a reaction when I click on stuff, namely crashing
RStudio.

**Comment by jgabry** [comment]
Ok that's a start. Does that give you different warnings/errors in the
chrome dev tools window than before?

**Comment by bgoodri** [comment]
No. The connection between RStudio and Chrome goes down when RStudio
crashes.

**Comment by jgabry** [comment]
Rob double checked that it works fine with his Ubuntu 16.04 system (and it
does) so I'm not sure what's up with yours. Are you using Ubuntu? Arch?

**Comment by bgoodri** [comment]
Debian. My guess is that some underlying library was updated. My versions
are a good bit ahead of an Ubuntu 16.04.
