### ISSUE TITLE
Some parameters not shown in the diagnose tab

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/shinystan#155]
When fitting a model with the latest dev version of brms and then calling shinystan, some parameters cannot be selected in the diagnose tab. These parameters happen to be the ones for which i changed the `fnames` element within the `stanfit` object. In the estimate tab, all parameters are visible. Here is an example:

```R
library(brms)
fit <- brm(count ~ log_Base4_c * Trt_c + (1|patient),
           data = epilepsy, family = poisson())
launch_shinystan(fit, TRUE)
```

Is this a problem in brms that should be fixed from my side?

**Comment by jgabry** [comment]
Hmm, I'll need to dig into this a bit because it's been a while since I
wrote the code in shinystan that handles the parameter selection.

**Comment by paul-buerkner** [comment]
Any progress on this one? I have looked that shinystan code base and I couldn't find the place where is is happening. Basically, the reason will be that for renamed parameters, the parameter names no longer coincide with `<parameter>[index]>`, and thus won't be recognized. For instance, in brms a parameter vector not appearing in the diagnose tab is named `b`, because its elements are no longer named `b[1], b[2]` etc. but `b_x` and `b_y`, say. One fix could be to identify parameters with associated elements by position (in the list of parameters) rather by name. I haven't tried it recently, but I can remember rstanarm having the same issue at some point.

**Comment by ecologics** [comment]
Wondering too if there has been any progress on this. `shinystan` used to work well with `brms`, but @paul-buerkner confirms that it is not a change with `brms` that is at fault.

Would be fabulous to have this working again, as `shinystan` really is a fabulous and efficient tool.

**Comment by jgabry** [comment]
Thanks for reminding me about this. I'll look into this and get it fixed.

**Comment by paul-buerkner** [comment]
That make generally sense. I have a few questions / comments though:

1. How exactly should the names of  `param_dims` correspond to `param_names`?
2. Conditional on the answer of 1. this may be a lot of code overhead in brms. I used to rename the `stanfit@sim$dims_oi` and `stanfit@sim$pars_oi` as well, but unfortunately, this broke compatibility with the **bridgesampling** package, so I removed the corresponding code. Is there possibly a better solution to this problem?
3. If I remember it correctly, **rstanarm** also only renames `stanfit@sim$fnames_oi` so I would expect it to have the same problems as brms. If that's true, wouldn't it make more sense to think of a more general solution?

**Comment by jgabry** [comment]
Ok this deserves more attention than I can give it at the moment, but lets
come back to this in a few days once we get the loo v2 update out, and
rstanarm and brms. we’ll find a good general solution.

**Comment by paul-buerkner** [comment]
I can confirm your PR fixes this form the brms side. Shell we close this issue now?

**Comment by jgabry** [comment]
Yeah I’ll close this. Glad that worked!
