### ISSUE TITLE
Allow subsetting of vector/matrix model params when making shinystan object

### ISSUE THREAD

**Issue by jan-glx** [stan-dev/shinystan#156]
Extending #122 : 
If fit models with large vector and matrix parameters in stan. To inspect the fits in shinystan I have to exclude these parameters using the `pars` argument of `as.shinystan` (otherwise shinystan becomes unresponsive and I am no longer able to select most of the parameters (dropdowns filled with matrix parameters)). In order to inspect the behavior of the matrix/vector parameters it would be great if it was possible to inspect a (random) subset of their elements with shinystan.

**Comment by VeenDuco** [comment]
We are currently working on version 3.0. Because of the new version we are currently closing old issues as a clean-up for version 3.0 such that we have a new overview of current open issues. 

Best, Duco

**Comment by jan-glx** [comment]
Does that mean it has been, will be or will never be implemented; or just that you are to busy to check?

**Comment by VeenDuco** [comment]
Hello Jan, 

Do you perhaps have an example that I could run so that I can see the problem and can try to figure out if there is a straight-forward way to implement this? 

Best, Duco
