### ISSUE TITLE
Reduce white space above multi-parameter plot when many parameters are selected

### ISSUE THREAD

**Issue by jgabry** [stan-dev/shinystan#16]
This is only noticeable for models with very many parameters (so not the demo) and also only if they decide to plot many of them at once.

**Comment by Felipe-Osorio** [comment]
nice. btw, I think this also happens on the bottom margin, in case you haven't already changed that. e.g. 
![image](https://cloud.githubusercontent.com/assets/7633431/12242166/72cc994a-b865-11e5-9be4-b7e88b08825a.png)

**Comment by jgabry** [comment]
Thanks! I hadn't noticed the bottom margin.
