### ISSUE TITLE
Installation issue with ubuntu

### ISSUE THREAD

**Issue by Vaugoyeau** [stan-dev/shinystan#160]
Hi,
I am a newbie with linux and githhub, so I am sorry in advance if solution is somewhere, I did not find it.

I try to install shinystan and I have an issue to do it.

I use:
devtools::install_github("stan-dev/shinystan")

And I have this message:

Warning: S3 methods ‘print.stanfit’, ‘as.array.stanfit’, ‘as.matrix.stanfit’, ‘as.data.frame.stanfit’, ‘is.array.stanfit’, ‘dim.stanfit’, ‘dimnames.stanfit’, ‘names.stanfit’, ‘names<-.stanfit’, ‘pairs.stanfit’ were declared in NAMESPACE but not found
Error in library.dynam(lib, package, package.lib) : 
  shared object ‘rstan.so’ not found
Error : unable to load R code in package ‘shinystan’
ERROR: lazy loading failed for package ‘shinystan’
* removing ‘/home/marie/R/x86_64-pc-linux-gnu-library/3.4/shinystan’
Installation failed: Command failed (1)

Could you help me please?

**Comment by jgabry** [comment]
Hmm, do you have rstan installed? I think the problem is that rstan is not installed or not installed properly.

**Comment by Vaugoyeau** [comment]
Thank you for your answer
I installed again rstan and it works!
