### ISSUE TITLE
Visualize sampled parameters from posterior predictive check

### ISSUE THREAD

**Issue by alexandrahotti** [stan-dev/shinystan#174]
Hi!

I want to use shiny stan to visualize a posterior predictive check from my stan_glm model. However, I would also like to see the corresponding posterior samples generated during the posterior predictive check. 

I am thinking that this is what I am supposed to be able to do at the following path in shiny stan: DIAGNOSE/PPcheck/Select data. Here I should be able to pick a parameter and then draw samples from its posterior using the option: “Select yrep (posterior predictive replications) - Parameter/generated quantity from model”. 

However, I do not know how to specify “Object from global environment” as well as “Parameter/generated quantity from model”. Is there perhaps some example on how to achieve this?

Thanks in advance!
Alex

**Comment by alexandrahotti** [comment]
**Update** 
I think that the way to go here is: 

`extract(stan_glm_model$stanfit)`

**Comment by VeenDuco** [comment]
Sorry for the late response. I'm glad you found a way to go forward! Best, Duco
