### ISSUE TITLE
Error with `launch_shinystan_demo`

### ISSUE THREAD

**Issue by e5c** [stan-dev/shinystan#177]
Hi, I'm hoping someone can help me with this.

I'm in a docker container using R from Jupyter. I build it with port forwarding `-p 9999:9999` for the shinystan app, and get this error: `stop("'browser' must be a non-empty character string")`

![image](https://user-images.githubusercontent.com/6350854/79487394-2cdb5a00-7fe6-11ea-87a7-531d1f74c777.png)

Cf. [Issue #172](https://github.com/stan-dev/shinystan/issues/172) I thought that running `devtools::install_github("stan-dev/shinystan", ref = "v3-alpha", build_vignettes = TRUE)` might help. Running with `options(shiny.launch.browser=FALSE)` results in this: 

![image](https://user-images.githubusercontent.com/6350854/79487648-952a3b80-7fe6-11ea-9701-924f26a09838.png)

and `localhost:9999` in my browser has nothing. 

Update: adding `options(shiny.host="0.0.0.0")` to the 2nd workflow allowed it to work! Closing this issue.

**Comment by VeenDuco** [comment]
Hello Eliza,

Very happy to hear that you figured out how to solve this! Thanks for posting the update here too on how you did so.

Best, Duco
