### ISSUE TITLE
Add support for CmdStanR objects

### ISSUE THREAD

**Issue by jgabry** [stan-dev/shinystan#184]
It should be pretty easy to add support for the fitted model objects from CmdStanR. 

For models fit using MCMC, there are a few options: 

* as.shinystan could convert a CmdStanMCMC object `fit` to stanfit with `rstan::read_stan_csv(fit$output_files())` and then just use the shinystan with the stanfit object

* as.shinystan could extract all the needed info from the CmdStanMCMC object and then use the array method for as.shinystan but also specify the argument to add the sampler_diagnostics, the number of warmup draws, etc. 

The second option is probably more efficient, but the first option requires less work.

**Comment by jgabry** [comment]
For anyone who see this right now and wants to use shinystan after using cmdstanr you can do: 

```r
stanfit <- rstan::read_stan_csv(fit$output_files())
launch_shinystan(stanfit)
```

**Comment by jgabry** [comment]
@VeenDuco I just added initial support for this on master and v3-alpha.

**Comment by nikunj410** [comment]
Can you add a worked simple working code for illustration?
