### ISSUE TITLE
shinyStan license

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/shinystan#26]
shinyStan needs an explicitly stated license.  

The options are

* BSD (what Stan C++ and CmdStan use)
* GPLv3 (what R, RStan, and PyStan use)

BSD is more liberal in the sense that it's more flexible for users.  But even if shinyStan is BSD, the combination of shinyStan + R is going to have the same copyleft (GPL) implications as R itself.  So probalby GPLv3 would be easier.  It'll also make it easier when you write it up for JStatSoft :-)

I'm still unhappy about PyStan using GPLv3 because Python isn't as restrictive as R, but it's what Allen wanted to go with.

I'm about to update the Stan web pages to include a link to shinyStan and I'll indicate that it's GPLv3.

**Comment by jgabry** [comment]
Ok great, thanks Bob. It's already listed as GPLv3 (for that very reason) in its R package description file so I'll just keep it that way going forward too.

**Comment by bob-carpenter** [comment]
It just needs to be listed somewhere on the GitHub page.  Maybe it is and I just don't see it?  I tried to make it very explicit for Stan on the home wiki page.

**Comment by jgabry** [comment]
There's a file called [LICENSE](https://github.com/stan-dev/shinystan/blob/develop/LICENSE) in the repository but I forgot to put something in the readme. I can add it to the readme and wiki

**Comment by bob-carpenter** [comment]
That'd be great.  I think just putting it on the top-level
README would be enough, though it wouldn't hurt to put it
on the Wiki.

I'm just very sensitive to licensing issues after fifteen
years in industry.

- Bob

**Comment by jgabry** [comment]
Thinking about licensing is very new to me so I'm glad you're sensitive to it. Whatever you think is best works for me.

**Comment by jgabry** [comment]
Ok, added to bottom of readme and added link in the wiki. Thanks for bringing this up.
