### ISSUE TITLE
Wiki landing page and index

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/shinystan#27]
Currently, the top-level Wiki page is redundant with the installation page.  I'd suggest following the pattern used by Stan itself to have the landing Wiki page be an index and description of what's available.  At least until there's another web page for shinyStan I can link to from the Stan home page.

**Comment by jgabry** [comment]
Good point. I just made that change. How's [this?](https://github.com/stan-dev/shinystan/wiki)

**Comment by syclik** [comment]
Looks good to me.

**Comment by bob-carpenter** [comment]
Great.  Thanks.  

- Bob

**Comment by jgabry** [comment]
Ok, I'm gonna close this issue. (Actually, I should ask: in general, what's the right protocol for closing issues? Do I close them or do I let the people who started them close them?)

**Comment by jgabry** [comment]
Thanks for adding shinyStan to the website too! One thing: under
'Applicability' we don't list Stan! I mean, it's obviously implied since
it's on the the Stan website, but maybe we should put Stan first on the
applicability list?

**Comment by jgabry** [comment]
Apparently I can do that (thanks Daniel), so I'll take care of it.

**Comment by bob-carpenter** [comment]
Ideally, you'd do a pull request and get someone else to
do code review, then everything would pass unit tests, 
and only then be merged by whoever wants to do it.

We've only been imposing this heavier process on Stan, though.
Even RStan's not going through the whole code review and unit
testing rigamarole.  It's really a matter of person power
more than anything else.

- Bob
