### ISSUE TITLE
Installation fails when building vignettes

### ISSUE THREAD

**Issue by vietgreek** [stan-dev/shinystan#33]
I have knitr version 1.9, and the installation appears to ensure that I have the latest version of knitr when it runs, but I am still getting the error message:

    Error: processing vignette 'using-shinyStan.Rmd' failed with diagnostics:
    'html_vignette' is not an exported object from 'namespace:rmarkdown'

This prevents the installation from completing.

**Comment by jgabry** [comment]
Sorry it's not working for you. What version of the `rmarkdown` package do you have? 

It's a strange error because `html_vignette` is definitely exported from `namespace:rmarkdown`. If you used the `install_shinystan` function then all other dependencies should be up to date so you can try installing shinyStan without building the vignettes by running

    devtools::install_github("stan-dev/shinystan", build_vignettes = FALSE) 

Let me know if that works for you.

**Comment by vietgreek** [comment]
Thanks for your help and the super-prompt reply!  Initially I was able to get around the problem just by copying the install_shinystan code and setting build_vignettes = FALSE.  Then I ran into some issues with the shiny package (I couldn't even get the basic shiny examples to run out of the box without crashing R) and wound up updating all of my packages through RStudio, and that seems to have fixed all of my issues, including the installation of shinyStan with build_vignettes = TRUE.

Sorry that this isn't very helpful -- I'm not sure which version of rmarkdown I was on, although I do know that I was on knitr 1.9.  Obviously my general package setup was somewhat dysfunctional but I don't know exactly how.

Really looking forward to playing with shinyStan, it looks great.  Thanks again.

**Comment by bob-carpenter** [comment]
@vietgreek:  Thanks for looking.

**Comment by bob-carpenter** [comment]
Thanks for looking and glad it's working for you now

It's no big deal if we can't track down incompatibilities
with older versions of packages.  We already require
fairly up-to-date vesions of R, Rcpp, RcppEigen, and BH.

- Bob

**Comment by jgabry** [comment]
Happy to help. Glad it's working for you!
