### ISSUE TITLE
summary stats table resets when changing decimal places

### ISSUE THREAD

**Issue by jgabry** [stan-dev/shinystan#6]
From Bob Carpenter on stan-dev:

> I went into view table options and changing decimal places reset everything --- this is probably not what you want to happen in general.  Destructive ops with no "back" button need strong warnings to users, maybe in the form of a modal dialog box.

**Comment by jgabry** [comment]
I think this will have to be solved with javascript (jquery) not R because need to prevent [DataTables](http://www.datatables.net/) from resetting all filters.

**Comment by VeenDuco** [comment]
We are currently closing old issues as a clean-up for version 3.0 such that we have a new overview of current open issues.
