### ISSUE TITLE
warning about disabled javascript

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/shinystan#77]
Many people include the NoScript or similar add-ons that block JavaScript execution by default. In that case, shinystan launches but does not do much of anything. In that case, there should be a warning / explanation somewhere that the user should allow JavaScript to execute from that local URL.

**Comment by jgabry** [comment]
That's a good point. I never thought of that. Do you think a note in the
launch_shinystan function documentation is sufficient?

**Comment by bgoodri** [comment]
Ideally, generate a message in the webbrowser if JavaScript is disabled but
failing that, then warnings all over the place is the next best thing.

**Comment by bob-carpenter** [comment]
I think people disabling JavaScript should be used to
pretty much nothing working on the web.

- Bob

**Comment by bgoodri** [comment]
They might be using a foreign computer and / or expecting it to work for
local URLs but not have the shinystan port whitelisted.

**Comment by andrewgelman** [comment]
Just by the way—I’m pretty sure this was _not_ the bug that caused Shinystan to fail for me.

P.S.  I hate camelcase.  Shinystan, ShinyStan, shinyStan, I can never remember which it is.  It’s weird that the package is shinyStan but the R function is launch_shinystan without the capital S.

**Comment by jgabry** [comment]
I know. I'm regretting it. Is it too late to just change the package name to shinystan?

**Comment by jgabry** [comment]
@bgoodri Whenever you have a chance can you try reinstalling from the shinystan2 branch and opening in a browser with disabled javascript? It should now display a big warning in orange. Seems to work, but I'd like someone else to try it too before I close the issue. Thanks.

**Comment by bgoodri** [comment]
I get
```

> devtools::install_github("stan-dev/shinystan", ref = "shinystan2")Downloading github repo stan-dev/shinystan@shinystan2Installing shinystanSkipping 1 packages ahead of CRAN: DT'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/tmp/Rtmp8Tr9gm/devtools4e5b25416ac2/stan-dev-shinystan-0c73594'  \
  --library='/usr/local/lib/R/site-library' --install-tests *
installing *source* package ‘shinystan’ ...** R** data*** moving
datasets to lazyload DB** inst** tests** preparing package for lazy
loadingError in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()),
versionCheck = vI[[j]]) :
  namespace ‘reshape2’ 1.4 is already loaded, but >= 1.4.1 is
requiredERROR: lazy loading failed for package ‘shinystan’* removing
‘/usr/local/lib/R/site-library/shinystan’Error: Command failed (1)```

even though I have reshape2 1.4.1.


Ben


On Fri, Aug 7, 2015 at 6:28 PM, Jonah Gabry <notifications@github.com>
wrote:

> @bgoodri <https://github.com/bgoodri> Whenever you have a chance can you
> try reinstalling from the shinystan2 branch and opening in a browser with
> disabled javascript? It should now display a big warning in orange. Seems
> to work, but I'd like someone else to try it too before I close the issue.
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stan-dev/shinystan/issues/77#issuecomment-128847918>.
>

**Comment by jgabry** [comment]
Weird. Well, I removed the version requirement for reshape2 from the
description file. Does that get rid of the error? I just tried
install_github myself and it seems to work fine.

**Comment by bgoodri** [comment]
Yes it seems fine now.

**Comment by jgabry** [comment]
I assume the javascript warning worked too?

**Comment by bgoodri** [comment]
Well, the usual message appeared at the top when it didn't work, which is
what most websites do.

**Comment by jgabry** [comment]
Ok can I close this issue or were you think we need more JavaScript
warnings?

**Comment by bgoodri** [comment]
Close it.
