### ISSUE TITLE
Allow renaming (or labelling) parameters

### ISSUE THREAD

**Issue by jgabry** [stan-dev/shinystan#8]
[From Ben on stan-dev:](https://groups.google.com/d/msg/stan-dev/ISiJ-re5MFQ/3WRcFWtlbB0J)

With the rstan on GitHub, it is technically possible to reassign names now, but you have to know what you are doing and it is difficult to then only print a subset of the renamed parameters.

So if shinyStan (whether offline or online) had a more convenient way to do this, I think it would help a lot.

**Comment by VeenDuco** [comment]
We are currently closing old issues as a clean-up for version 3.0 such that we have a new overview of current open issues.
