### ISSUE TITLE
error: subscript out of bounds

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/shinystan#88]
If you do
```
fit1 <- stan_glm(Volume ~ log(Girth) + log(Height), data = trees,  family = gaussian(link = 'log'))
launch_shinystan(fit1)
```
and go to NUTS (Plots), you get the error message and in the console it says
```
Error in samps_post_warmup[if (!is.null(sel)) sel, , "lp__"] : 
  subscript out of bounds
```
This may have to do with it being renamed "log-posterior"?

**Comment by jgabry** [comment]
It definitely has to do with the name change. I had not noticed that. Is
this changing in rstan too or are you just renaming it in rstanarm? If it's
just rstanarm then I can put in a special case for that.

**Comment by bgoodri** [comment]
It is just in rstanarm at the moment, but I could imagine any number of
packages the depend on Stan doing something like that. It may be best to
just call get_log_posterior() rather than rely on hard-coded names.

**Comment by jgabry** [comment]
If get_log_posterior is sticking around then yeah I'll just use that.
