### ISSUE TITLE
"Error: subscript out of bounds" when selecting "ALL theta" under "Estimates > Parameters plot" in demo.

### ISSUE THREAD

**Issue by samuelklee** [stan-dev/shinystan#95]
This seems to work correctly in the online demo http://jgabry.shinyapps.io/ShinyStan2Preview but raises

```Error in samps[, , params] : subscript out of bounds```

when I run launch_shinystan_demo() locally (or when I try to select parameter blocks for my own posterior samples).  I'm running from within Rstudio and get the error under both R 3.1.2 and R 3.2.2 in Ubuntu 14.04.

Thanks!

**Comment by jgabry** [comment]
Thanks for reporting the error. Definitely a bug. This only happens when
you use the shortcut for selecting all of the thetas and not if you plot
all of them by adding them to the plot one at a time right?

**Comment by samuelklee** [comment]
Yup, that appears to be the case.

**Comment by jgabry** [comment]
Ok thanks. I think this shouldn't be too hard to fix. I'll reply again and
let you know when I have it working.

Oh and one last question for now, is your version of shinystan 2.0.0 or
2.0.1?

Thanks,

Jonah

**Comment by samuelklee** [comment]
2.0.1.  Thanks for the quick response!

**Comment by jgabry** [comment]
Ok, I think it's fixed. If you update shinystan from the branch with the fix like this:

    devtools::install_github("stan-dev/shinystan", ref = "bugfix-issue-95")

I think you shouldn't get the error anymore. Whenever you have a chance, if you don't mind trying that and letting me know that would be helpful. Thanks!

**Comment by samuelklee** [comment]
Excellent, looks like that fixed it.  Thanks again for the lightning-fast response (and for your work on this package---it's pretty awesome!)

**Comment by jgabry** [comment]
Ok great, thanks.

Glad you like the package! And thanks again for reporting the error.

**Comment by jgabry** [comment]
Fixed in 7c7e3d2
