### ISSUE TITLE
specify parameters by regexp

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/shinystan#97]
Particularly for something like an object produced by stan_glmer, it is tedious to specify which group-level parameters you want to plot or whatever because they are not part of a larger array. In this case, it would be nice if you could specify all parameters that match a regular expression.

**Comment by jgabry** [comment]
Thanks. This would be quite useful. I've been meaning to do something like
this but I forgot to create an issue (and so forgot to do it).

**Comment by jgabry** [comment]
@bgoodri Does the [regex-selection](https://github.com/stan-dev/shinystan/tree/regex-selection) branch do what you had in mind?

**Comment by bgoodri** [comment]
Yeah
