### ISSUE TITLE
shiny and stan look for "shinyStan" but package is "shinystan" -- case matters in R

### ISSUE THREAD

**Issue by apollostream** [stan-dev/shinystan#98]
Hi,
I've successfully installed package "shinystan" from CRAN (and have also successfully installed it from GitHub).

If I try to run "stan(...)" , I get the following error message:
> mcmcStan <- stan(file = 'mymodel.stan', data = myData, chains = 0) # Prep run ("chains=0") to compile model.
Loading required package: shinyStan
Error in .requirePackage(package) : 
  unable to find required package ‘shinyStan’
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘shinyStan’

Or even if I try to reinstall shiny (just fishing), R complains:
> install.packages("shiny")
Loading required package: shinyStan
Error in .requirePackage(package) : 
  unable to find required package ‘shinyStan’
Installing package into ‘C:/xxxxxxxxxxxx/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/shiny_0.12.2.zip'
Content type 'application/zip' length 1866824 bytes (1.8 MB)
downloaded 1.8 MB

Note that the asked for package name in the error message is camelcase "shinyStan", which of course is not the same as the all lowercase name of the actual installed package "shinystan".

Am I missing something?  How do I get stan to run again -- I've only had this problem since upgrading to the latest version of rstan?

Thanks.

**Comment by jgabry** [comment]
Hmm, this is very strange.

An old version of shinystan was called shinyStan, but that was before the
CRAN versions. But that shouldn't affect anything here, especially because
rstan doesn't require you to have shinystan.

Did you by any chance save an object creating by an old version of
shinystan (back when it was called shinyStan) in the same working directory
as your Stan model? Or maybe it's trying to load a saved workspace?

**Comment by apollostream** [comment]
I believe an old object or option setting must have been retained in the environment. After restarting RStudio (and of course R), rstan and shinystan ran just fine.
Thank you!
On Oct 28, 2015 12:53 PM, Jonah Gabry <notifications@github.com> wrote:Hmm, this is very strange.

An old version of shinystan was called shinyStan, but that was before the
CRAN versions. But that shouldn't affect anything here, especially because
rstan doesn't require you to have shinystan.

Did you by any chance save an object creating by an old version of
shinystan (back when it was called shinyStan) in the same working directory
as your Stan model? Or maybe it's trying to load a saved workspace?

**Comment by jgabry** [comment]
Glad it's working now!
